name: main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: for i in {1..24}; do echo "sleeping"; sleep 5; done; exit 1;
  
